
/**
Constructor
Do not call Function in Constructor.
*/
class subcard()
{
	super();

	//TODO:edit here

}
extends AView;


function subcard*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subcard*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subcard*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
