
/**
Constructor
Do not call Function in Constructor.
*/
class submain()
{
	super();

	//TODO:edit here

}
extends AView;


function submain*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function submain*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function submain*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
