
/**
Constructor
Do not call Function in Constructor.
*/
class subpannel2()
{
	super();

	//TODO:edit here

}
extends AView;


function subpannel2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subpannel2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subpannel2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
